from enum import Enum

class ErrorCode(Enum):
    REVIEWER_ERROR = "ERR020"
    REVIEWER_SPECIFIC_ERROR = "ERR020_1"
    PLANNER_ERROR = "ERR021"
    PLANNER_VALIDATION_ERROR = "ERR021_1"
    PRIORITIZER_ERROR = "ERR022"
    PRIORITIZER_MODEL_LOAD_ERROR = "ERR022_1"
    PRIORITIZER_DATA_VALIDATION_ERROR = "ERR022_2"
